export const data = [
    {
        id: 1, 
        dateOfBirth: "2013-04-27",
        name: "Eloisa",
        eyesColor: "Chocolate",
    },
    {
        id: 2, 
        dateOfBirth: "1989-03-04",
        name: "Ibby",
        eyesColor: "DeepSkyBlue",
    },
    {
        id: 3, 
        dateOfBirth: "1980-04-02",
        name: "Quintilla",
        eyesColor: "LightSlateGrey",
    },
    {
        id: 4, 
        dateOfBirth: "2020-01-10",
        name: "Klarrisa",
        eyesColor: "Fuchsia",
    },
    {
        id: 5, 
        dateOfBirth: "1983-04-03",
        name: "Cathryn",
        eyesColor: "LightSeaGreen",
    },
    {
        id: 6, 
        dateOfBirth: "2015-07-03",
        name: "Dreddy",
        eyesColor: "DarkMagenta",
    },
    {
        id: 7, 
        dateOfBirth: "1997-03-12",
        name: "Erena",
        eyesColor: "DimGrey",
    },
    {
        id: 8, 
        dateOfBirth: "2019-02-25",
        name: "Tory",
        eyesColor: "FloralWhite",
    },
    {
        id: 9, 
        dateOfBirth: "2008-05-28",
        name: "Concordia",
        eyesColor: "Purple",
    },
    {
        id: 10, 
        dateOfBirth: "1993-10-30",
        name: "Edithe",
        eyesColor: "OrangeRed",
    },
    {
        id: 11, 
        dateOfBirth: "2015-08-27",
        name: "Mimi",
        eyesColor: "PaleTurquoise",
    },
    {
        id: 12, 
        dateOfBirth: "2016-02-02",
        name: "Violetta",
        eyesColor: "Thistle",
    },
    {
        id: 13, 
        dateOfBirth: "2018-12-27",
        name: "Hedvig",
        eyesColor: "White",
    },
    {
        id: 14, 
        dateOfBirth: "1983-11-11",
        name: "Pet",
        eyesColor: "BurlyWood",
    },
    {
        id: 15, 
        dateOfBirth: "2001-05-07",
        name: "Malissa",
        eyesColor: "DarkBlue",
    },
    {
        id: 16, 
        dateOfBirth: "2007-09-09",
        name: "Brittani",
        eyesColor: "PowderBlue",
    },
    {
        id: 17, 
        dateOfBirth: "1997-02-20",
        name: "Antonia",
        eyesColor: "DarkKhaki",
    },
    {
        id: 18, 
        dateOfBirth: "1993-12-03",
        name: "Mariam",
        eyesColor: "Orchid",
    },
    {
        id: 19, 
        dateOfBirth: "2016-06-30",
        name: "Lark",
        eyesColor: "DimGray",
    },
    {
        id: 20, 
        dateOfBirth: "2006-08-18",
        name: "Aurelea",
        eyesColor: "DarkGoldenRod",
    },
    {
        id: 21, 
        dateOfBirth: "1987-06-25",
        name: "Lucila",
        eyesColor: "SaddleBrown",
    },
    {
        id: 22, 
        dateOfBirth: "1984-03-18",
        name: "Colline",
        eyesColor: "YellowGreen",
    },
    {
        id: 23, 
        dateOfBirth: "2018-12-11",
        name: "Arabelle",
        eyesColor: "Brown",
    },
    {
        id: 24, 
        dateOfBirth: "2019-01-26",
        name: "Vinny",
        eyesColor: "Navy",
    },
    {
        id: 25, 
        dateOfBirth: "2006-01-04",
        name: "Queenie",
        eyesColor: "Khaki",
    },
    {
        id: 26, 
        dateOfBirth: "1990-05-17",
        name: "Blondy",
        eyesColor: "DarkOrchid",
    },
    {
        id: 27, 
        dateOfBirth: "2000-07-28",
        name: "Cate",
        eyesColor: "LawnGreen",
    },
    {
        id: 28, 
        dateOfBirth: "2000-12-09",
        name: "Max",
        eyesColor: "Chocolate",
    },
    {
        id: 29, 
        dateOfBirth: "2023-09-06",
        name: "Carina",
        eyesColor: "CornflowerBlue",
    },
    {
        id: 30, 
        dateOfBirth: "1995-03-17",
        name: "Caitrin",
        eyesColor: "Fuchsia",
    },
    {
        id: 31, 
        dateOfBirth: "1990-04-11",
        name: "Randi",
        eyesColor: "FireBrick",
    },
    {
        id: 32, 
        dateOfBirth: "2021-08-23",
        name: "Jerrylee",
        eyesColor: "DarkGreen",
    },
    {
        id: 33, 
        dateOfBirth: "2016-07-19",
        name: "Zulema",
        eyesColor: "Purple",
    },
    {
        id: 34, 
        dateOfBirth: "2014-04-10",
        name: "Marje",
        eyesColor: "Orange",
    },
    {
        id: 35, 
        dateOfBirth: "2016-07-28",
        name: "Christy",
        eyesColor: "Silver",
    },
    {
        id: 36, 
        dateOfBirth: "1990-01-31",
        name: "Bernadina",
        eyesColor: "LightBlue",
    },
    {
        id: 37, 
        dateOfBirth: "1989-05-06",
        name: "Brier",
        eyesColor: "LightCyan",
    },
    {
        id: 38, 
        dateOfBirth: "1980-01-22",
        name: "Bernardina",
        eyesColor: "DarkGoldenRod",
    },
    {
        id: 39, 
        dateOfBirth: "2008-01-24",
        name: "Gypsy",
        eyesColor: "Pink",
    },
    {
        id: 40, 
        dateOfBirth: "2024-08-17",
        name: "Leontyne",
        eyesColor: "PaleVioletRed",
    },
    {
        id: 41, 
        dateOfBirth: "1990-05-10",
        name: "Valida",
        eyesColor: "MistyRose",
    },
    {
        id: 42, 
        dateOfBirth: "2006-06-27",
        name: "Carena",
        eyesColor: "Violet",
    },
    {
        id: 43, 
        dateOfBirth: "2003-06-10",
        name: "Peggy",
        eyesColor: "PeachPuff",
    },
    {
        id: 44, 
        dateOfBirth: "1990-06-20",
        name: "Giralda",
        eyesColor: "GreenYellow",
    },
    {
        id: 45, 
        dateOfBirth: "1988-05-28",
        name: "Druci",
        eyesColor: "RosyBrown",
    },
    {
        id: 46, 
        dateOfBirth: "1980-09-21",
        name: "Jaquelin",
        eyesColor: "Crimson",
    },
    {
        id: 47, 
        dateOfBirth: "1998-03-06",
        name: "Domini",
        eyesColor: "Green",
    },
    {
        id: 48, 
        dateOfBirth: "1981-03-06",
        name: "Gwennie",
        eyesColor: "Snow",
    },
    {
        id: 49, 
        dateOfBirth: "2007-02-03",
        name: "Madelaine",
        eyesColor: "MintCream",
    },
    {
        id: 50, 
        dateOfBirth: "2012-02-19",
        name: "Geralda",
        eyesColor: "MediumAquaMarine",
    },
    {
        id: 51, 
        dateOfBirth: "2009-10-08",
        name: "Aline",
        eyesColor: "LightGrey",
    },
    {
        id: 52, 
        dateOfBirth: "2022-05-21",
        name: "Prudi",
        eyesColor: "Salmon",
    },
    {
        id: 53, 
        dateOfBirth: "1980-08-07",
        name: "Bella",
        eyesColor: "HotPink",
    },
    {
        id: 54, 
        dateOfBirth: "2022-01-21",
        name: "Dianne",
        eyesColor: "BlueViolet",
    },
    {
        id: 55, 
        dateOfBirth: "1991-06-21",
        name: "Rubi",
        eyesColor: "DarkMagenta",
    },
    {
        id: 56, 
        dateOfBirth: "2007-12-27",
        name: "Cyndie",
        eyesColor: "DarkOrchid",
    },
    {
        id: 57, 
        dateOfBirth: "2001-02-15",
        name: "Colene",
        eyesColor: "Cyan",
    },
    {
        id: 58, 
        dateOfBirth: "2009-07-21",
        name: "Corette",
        eyesColor: "FireBrick",
    },
    {
        id: 59, 
        dateOfBirth: "2024-08-25",
        name: "Anstice",
        eyesColor: "Crimson",
    },
    {
        id: 60, 
        dateOfBirth: "2023-10-10",
        name: "Billye",
        eyesColor: "Fuchsia",
    },
    {
        id: 61, 
        dateOfBirth: "1983-03-10",
        name: "Auberta",
        eyesColor: "GreenYellow",
    },
    {
        id: 62, 
        dateOfBirth: "2016-01-12",
        name: "Zitella",
        eyesColor: "Peru",
    },
    {
        id: 63, 
        dateOfBirth: "2018-06-23",
        name: "Naomi",
        eyesColor: "DarkBlue",
    },
    {
        id: 64, 
        dateOfBirth: "1980-09-18",
        name: "Anny",
        eyesColor: "MistyRose",
    },
    {
        id: 65, 
        dateOfBirth: "2015-05-03",
        name: "Charline",
        eyesColor: "Darkorange",
    },
    {
        id: 66, 
        dateOfBirth: "2021-11-19",
        name: "Odessa",
        eyesColor: "MediumBlue",
    },
    {
        id: 67, 
        dateOfBirth: "2003-11-15",
        name: "Laurene",
        eyesColor: "DarkSlateGrey",
    },
    {
        id: 68, 
        dateOfBirth: "2006-04-16",
        name: "Jenilee",
        eyesColor: "PaleVioletRed",
    },
    {
        id: 69, 
        dateOfBirth: "2023-06-18",
        name: "Hollie",
        eyesColor: "MintCream",
    },
    {
        id: 70, 
        dateOfBirth: "1998-09-08",
        name: "Bambie",
        eyesColor: "DodgerBlue",
    },
    {
        id: 71, 
        dateOfBirth: "2024-02-24",
        name: "Lilli",
        eyesColor: "Aquamarine",
    },
    {
        id: 72, 
        dateOfBirth: "1981-08-27",
        name: "Carilyn",
        eyesColor: "MediumBlue",
    },
    {
        id: 73, 
        dateOfBirth: "2008-09-04",
        name: "Ashla",
        eyesColor: "RoyalBlue",
    },
    {
        id: 74, 
        dateOfBirth: "2024-04-01",
        name: "Karin",
        eyesColor: "HotPink",
    },
    {
        id: 75, 
        dateOfBirth: "2003-08-14",
        name: "Camille",
        eyesColor: "MediumAquaMarine",
    },
    {
        id: 76, 
        dateOfBirth: "2008-12-14",
        name: "Hailee",
        eyesColor: "OliveDrab",
    },
    {
        id: 77, 
        dateOfBirth: "2011-01-18",
        name: "Vivia",
        eyesColor: "SlateGrey",
    },
    {
        id: 78, 
        dateOfBirth: "2003-06-07",
        name: "Petronella",
        eyesColor: "Cornsilk",
    },
    {
        id: 79, 
        dateOfBirth: "2023-04-12",
        name: "Milicent",
        eyesColor: "DarkKhaki",
    },
    {
        id: 80, 
        dateOfBirth: "2001-10-06",
        name: "Kylynn",
        eyesColor: "HotPink",
    },
    {
        id: 81, 
        dateOfBirth: "1988-04-22",
        name: "Lexy",
        eyesColor: "DarkRed",
    },
    {
        id: 82, 
        dateOfBirth: "1985-07-19",
        name: "Donelle",
        eyesColor: "DarkOrchid",
    },
    {
        id: 83, 
        dateOfBirth: "2012-03-17",
        name: "Cornelle",
        eyesColor: "MediumAquaMarine",
    },
    {
        id: 84, 
        dateOfBirth: "1997-11-01",
        name: "Dreddy",
        eyesColor: "MediumTurquoise",
    },
    {
        id: 85, 
        dateOfBirth: "2002-11-30",
        name: "Nicolea",
        eyesColor: "DeepPink",
    },
    {
        id: 86, 
        dateOfBirth: "2021-04-19",
        name: "Kerianne",
        eyesColor: "FireBrick",
    },
    {
        id: 87, 
        dateOfBirth: "2006-01-19",
        name: "Shalne",
        eyesColor: "SlateBlue",
    },
    {
        id: 88, 
        dateOfBirth: "1998-03-06",
        name: "Marie-Jeanne",
        eyesColor: "Purple",
    },
    {
        id: 89, 
        dateOfBirth: "2005-07-21",
        name: "Karlie",
        eyesColor: "SeaShell",
    },
    {
        id: 90, 
        dateOfBirth: "1981-10-04",
        name: "Marcellina",
        eyesColor: "LightSeaGreen",
    },
    {
        id: 91, 
        dateOfBirth: "2001-10-29",
        name: "Belvia",
        eyesColor: "Maroon",
    },
    {
        id: 92, 
        dateOfBirth: "1988-06-21",
        name: "Olva",
        eyesColor: "MidnightBlue",
    },
    {
        id: 93, 
        dateOfBirth: "2018-02-07",
        name: "Antonietta",
        eyesColor: "SkyBlue",
    },
    {
        id: 94, 
        dateOfBirth: "1989-03-10",
        name: "Lindsay",
        eyesColor: "MintCream",
    },
    {
        id: 95, 
        dateOfBirth: "2003-03-03",
        name: "Florenza",
        eyesColor: "LightCyan",
    },
    {
        id: 96, 
        dateOfBirth: "1981-08-27",
        name: "Sacha",
        eyesColor: "Chartreuse",
    },
    {
        id: 97, 
        dateOfBirth: "1990-06-06",
        name: "Bili",
        eyesColor: "MediumOrchid",
    },
    {
        id: 98, 
        dateOfBirth: "1982-05-24",
        name: "La Verne",
        eyesColor: "DarkSlateGray",
    },
    {
        id: 99, 
        dateOfBirth: "2017-04-15",
        name: "Brana",
        eyesColor: "Olive",
    },];